name: Exemplo out
run-name: exempo workflow para output exe po ${{github.actor}}
on:
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        outputs:
            output-shell: ${{ steps.exemplo-output.outputs.action_random }}
            output-generatedpassword: ${{ steps.generatedpassword.outputs.password }}
        steps:
            - name: output shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT

            - name: Exibindo os out da action_random
              run: echo "${{ steps.exemplo-output.outputs.action_random }}"

            - name: passworda
              id: generatedpassword
              uses: aammirmirza/RandomPasswordGenerator@v1.1
              with:
                 length: 15
            - name: mostran passworda
              run: echo "${{ steps.generatedpassword.outputs.password }}"
    exibindo-valores:
        needs: [gerando_output]
        runs-on: ubuntu-latest
        steps:
            - name: exibindo os out do out 
              run: |
                echo "out put shel do job needs : ${{needs.gerando_output.outputs.output-shell}}"
                echo "out put password do job needs : ${{needs.gerando_output.outputs.output-generatedpassword}}"