name: Exemplo out
run-name: exempo workflow para output exe po ${{github.actor}}
on:
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        steps:
            - name: output shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(($RANDOM))
                echo action_random = $ACTION_RANDOM >> $GITHUB_OUTPUT
            - name: Exibindo os out da action_random
              run: |
                echo "${{steps.exemplo-output.outputs.action_random}}"
