name: Workflow Matriz
on:
  workflow_dispatch
jobs:
  exemp-fluxo-exec:
    strategy:
      matrix:
        versao: [16,18,20]
        plataforma: ["windows, ubuntu"]
    runs-on: "${{ matrix.plataforma }} - latest"
    steps:
      - name: Instalacao do node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versao }}
      - name: Exibicao da versao e da plataform
        run: | 
          node --version
          echo ${{ runner.os }}

