name: wORKFLOW Evento
on:
  push:
jobs:
    apenas-main:
      if: ${{ github.ref == 'refs/heads/main' }}
      name: exec na branch main
      runs-on: ubuntu-latest
      steps:
        - name: Exec main
          run: echo "exec so na main"