name: Workflow Matriz2
on:
  workflow_dispatch:
jobs:
  exemp-fluxo-exec:
    strategy:
      matrix:
        version: [10, 12, 14]
        plataforma:  [ubuntu-latest, windows-latest]
    runs-on: "${{ matrix.plataforma }} - latest"
    steps:
      - name: Instalacao do node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Exibicao da versao e da plataform
        run: | 
          node --version
          echo ${{ runner.os }}

