name: wORKFLOW Evento
on:
  workflow_dispatch:
    inputs:
        valor_numerico:
          type: number
          default: 20
        valor_string:
          type: string
          default: "xpto"
        valor_boolean:
          type: boolean
          default: true
jobs:
    teste:
      permissions: write-all
      runs-on: ubunut-latest
      steps:
        - name: operação string
          run: echo "${{github.actor == inputs.valor_string}}"
        - name: operação number
          run: echo "${{inputs.valor_numerico > 20}}"
        - name: operação boolean
          run: echo "${{!inputs.valor_boolean}}"