name: wORKFLOW Evento
on:
  push:
jobs:
  exemp-f-01:
    runs-on: ubuntu-latest
    steps:
      - name: vai falhar
        run: 1
  exemp-f-02:
    runs-on: ubuntu-latest
    needs: [exemp-f-01]
    if: ${{ failure() }}
    steps:
      - name: vai da bom. 
        run: echo "vai assim mesmo"

